/* empty css                      */import{S as a,N as d}from"./assets/vendor-wKantkHV.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function h(){const r=window.innerWidth;r>=1440&&new a(".reviews-swiper",{modules:[d],loop:!0,slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".reviews-nav .custom-next",prevEl:".reviews-nav .custom-prev"},breakpoints:{374:{slidesPerView:1.1,spaceBetween:20},1440:{slidesPerView:4,spaceBetween:20}}});const o=new a(".gallery-swiper",{modules:[d],loop:!0,slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".gallery-nav .custom-next",prevEl:".gallery-nav .custom-prev"},breakpoints:{374:{slidesPerView:1.2,spaceBetween:10,centeredSlides:!0},1440:{slidesPerView:3,spaceBetween:40,centeredSlides:!1}}});r<=375&&o.slideToLoop(1,0)}document.addEventListener("DOMContentLoaded",h);document.querySelectorAll(".faq-acc-el-trigger").forEach(r=>{r.addEventListener("click",()=>{const o=r.closest(".faq-acc-el"),i=o.querySelector(".faq-acc-el-descr-frame"),n=o.querySelector(".faq-img");o.classList.contains("open")?(o.classList.remove("open"),n==null||n.classList.remove("rotated"),i&&(i.style.maxHeight="0")):(o.classList.add("open"),n==null||n.classList.add("rotated"),i&&(i.style.maxHeight=i.scrollHeight+"px"))})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),o=r.querySelector(".icon"),i=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header"),t=document.querySelector(".header-wrapper");let s=!1;const c=`
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M11.75 7.25H23M5 14H23H8.375M5 20.75H16.25" stroke="white" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round" />
    </svg>
  `,p=`
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M8.5 20.5L14.5 14.5L20.5 8.5M20.5 20.5L8.5 8.5" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
  `;r.addEventListener("click",()=>{s=!s,o.innerHTML=s?p:c,s?u():l()}),n.forEach(f=>f.addEventListener("click",()=>{l(),o.innerHTML=c,s=!1})),window.addEventListener("scroll",m);function u(){i.style.display="block",t&&(t.style.display="none")}function l(){i.style.display="none",t&&(t.style.display="")}function m(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const e=document.getElementById(n);if(!e)return;const t=r(),s=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:s,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",t=>{const s=e.getAttribute("href"),c=s.split("#")[1];(s.startsWith("#")||s.startsWith("index.html#")||s.startsWith("/index.html#"))&&(t.preventDefault(),o(c))})});const n=window.location.hash;if(n){const e=n.substring(1),t=()=>{document.getElementById(e)?o(e):requestAnimationFrame(t)};setTimeout(t,100)}}});document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),i=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(r.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),r.style.display="none"}),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),r.style.display="none"})});
//# sourceMappingURL=index.js.map
